# Generated by Django 5.2.4 on 2025-07-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('poly_arr', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('temp', models.DecimalField(decimal_places=8, max_digits=10)),
                ('feels_like', models.DecimalField(decimal_places=8, max_digits=10)),
                ('min_temp', models.DecimalField(decimal_places=8, max_digits=10)),
                ('max_temp', models.DecimalField(decimal_places=8, max_digits=10)),
                ('wind_speed', models.DecimalField(decimal_places=8, max_digits=10)),
                ('wind_gust', models.DecimalField(decimal_places=8, max_digits=10)),
                ('wind_degree', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('sea_level', models.IntegerField()),
                ('ground_level', models.IntegerField()),
                ('rain', models.IntegerField()),
                ('clouds', models.IntegerField()),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
    ]
