# Generated by Django 4.2.7 on 2025-07-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_router', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='feels_like',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='weather',
            name='max_temp',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='weather',
            name='min_temp',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='weather',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_gust',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_speed',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
