# Generated by Django 4.2.7 on 2025-07-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_router', '0002_alter_weather_feels_like_alter_weather_max_temp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventionMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SpreadMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentCure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CropDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('disease_name', models.CharField(max_length=200)),
                ('crop_affected', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=200)),
                ('possible_causal_agent', models.CharField(max_length=200)),
                ('common_symptoms', models.ManyToManyField(to='backend_router.symptom')),
                ('prevention', models.ManyToManyField(to='backend_router.preventionmeasure')),
                ('risk_causes', models.ManyToManyField(to='backend_router.riskfactor')),
                ('spread', models.ManyToManyField(to='backend_router.spreadmethod')),
                ('treatment', models.ManyToManyField(to='backend_router.treatmentcure')),
            ],
        ),
    ]
