# Generated by Django 4.2.7 on 2025-07-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_router', '0003_preventionmeasure_riskfactor_spreadmethod_symptom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
